export const Books = [
  {
    id: 1,
    title: "Rampage",
    author: "Lurline Naden",
    publishedDate: "11/11/2024",
    pages: 82,
    coverImage: "http://dummyimage.com/140x100.png/5fa2dd/ffffff",
    description: "High-quality matcha powder for smoothies and baking.",
  },
  {
    id: 2,
    title: "Empire of Dreams: The Story of the 'Star Wars' Trilogy",
    author: "Yolanthe Alwood",
    publishedDate: "2/17/2025",
    pages: 50,
    coverImage: "http://dummyimage.com/103x100.png/dddddd/000000",
    description:
      "Layered Greek yogurt with granola and mixed berries, ready to enjoy.",
  },
  {
    id: 3,
    title: "Night of the Living Dead 3D",
    author: "Sarge Loveless",
    publishedDate: "1/10/2025",
    pages: 4,
    coverImage: "http://dummyimage.com/246x100.png/ff4444/ffffff",
    description:
      "Custom engraved ID tags for pets with your contact information.",
  },
  {
    id: 4,
    title: "Little Red Flowers (Kan shang qu hen mei)",
    author: "Hugues Cogley",
    publishedDate: "8/5/2024",
    pages: 98,
    coverImage: "http://dummyimage.com/144x100.png/cc0000/ffffff",
    description:
      "Eco-friendly charger that uses solar energy for powering devices.",
  },
  {
    id: 5,
    title: "Sun Also Rises, The",
    author: "Ruthie Bram",
    publishedDate: "11/22/2024",
    pages: 46,
    coverImage: "http://dummyimage.com/230x100.png/ff4444/ffffff",
    description: "Stylish faux leather leggings for a trendy outfit.",
  },
  {
    id: 6,
    title: "Brats, The (Les gamins)",
    author: "Ertha Fernie",
    publishedDate: "10/3/2024",
    pages: 56,
    coverImage: "http://dummyimage.com/177x100.png/ff4444/ffffff",
    description: "Grilled chicken skewers glazed with teriyaki sauce.",
  },
  {
    id: 7,
    title: "Deuces Wild",
    author: "Laughton Boyn",
    publishedDate: "12/19/2024",
    pages: 36,
    coverImage: "http://dummyimage.com/239x100.png/5fa2dd/ffffff",
    description: "Sweet and chewy dried mango slices, perfect for snacking.",
  },
  {
    id: 8,
    title: "Volver",
    author: "Gene Duigan",
    publishedDate: "11/7/2024",
    pages: 98,
    coverImage: "http://dummyimage.com/155x100.png/cc0000/ffffff",
    description: "Grape leaves stuffed with rice and herbs, ready to eat.",
  },
  {
    id: 9,
    title: "Tale of Cinema (Geuk jang jeon)",
    author: "Davidson Hammel",
    publishedDate: "12/20/2024",
    pages: 18,
    coverImage: "http://dummyimage.com/148x100.png/dddddd/000000",
    description: "Organize travel documents, passport, and cards.",
  },
  {
    id: 10,
    title: "Fun on a Weekend",
    author: "Doti Gilliam",
    publishedDate: "1/19/2025",
    pages: 27,
    coverImage: "http://dummyimage.com/228x100.png/ff4444/ffffff",
    description:
      "Marinated grilled chicken breasts seasoned with garlic and herbs.",
  },
  {
    id: 11,
    title: "Butcher, The (Boucher, Le)",
    author: "Karen Flew",
    publishedDate: "6/21/2024",
    pages: 12,
    coverImage: "http://dummyimage.com/117x100.png/ff4444/ffffff",
    description: "Countertop dishwasher for small kitchens.",
  },
  {
    id: 12,
    title: "Country",
    author: "Horatia Eilert",
    publishedDate: "7/10/2024",
    pages: 94,
    coverImage: "http://dummyimage.com/118x100.png/5fa2dd/ffffff",
    description: "A light and breezy top ideal for warm days.",
  },
  {
    id: 13,
    title: "Love Is a Many-Splendored Thing",
    author: "Crichton Redfield",
    publishedDate: "5/25/2024",
    pages: 48,
    coverImage: "http://dummyimage.com/184x100.png/cc0000/ffffff",
    description: "A mix of frozen berries for smoothies or desserts",
  },
  {
    id: 14,
    title: "Snowmageddon",
    author: "Corbie Blundel",
    publishedDate: "4/25/2024",
    pages: 97,
    coverImage: "http://dummyimage.com/142x100.png/cc0000/ffffff",
    description: "Digital scale to avoid overweight baggage fees.",
  },
  {
    id: 15,
    title: "The Widow From Chicago",
    author: "Laurella Vaux",
    publishedDate: "9/22/2024",
    pages: 9,
    coverImage: "http://dummyimage.com/150x100.png/5fa2dd/ffffff",
    description:
      "A comfortable henley shirt made of soft cotton, perfect for casual outings.",
  },
  {
    id: 16,
    title: "Tarzan and His Mate",
    author: "Seymour Derx",
    publishedDate: "6/7/2024",
    pages: 40,
    coverImage: "http://dummyimage.com/203x100.png/5fa2dd/ffffff",
    description:
      "Rich tart filled with chocolate and raspberry, a gourmet dessert.",
  },
  {
    id: 17,
    title: "When Love Is Not Enough: The Lois Wilson Story",
    author: "Cort Valentetti",
    publishedDate: "9/4/2024",
    pages: 28,
    coverImage: "http://dummyimage.com/206x100.png/dddddd/000000",
    description:
      "Marinated chicken breasts coated in a sweet honey mustard glaze.",
  },
  {
    id: 18,
    title: "Coherence",
    author: "Rosabel Donaldson",
    publishedDate: "9/24/2024",
    pages: 29,
    coverImage: "http://dummyimage.com/106x100.png/cc0000/ffffff",
    description: "Reusable gel ice pack for injuries and cooling.",
  },
  {
    id: 19,
    title: "Teddy Bear (Mis)",
    author: "Heath Burnhams",
    publishedDate: "10/14/2024",
    pages: 36,
    coverImage: "http://dummyimage.com/230x100.png/cc0000/ffffff",
    description:
      "Rechargeable screwdriver with multiple bits for DIY projects.",
  },
  {
    id: 20,
    title: "I Don't Want to Sleep Alone (Hei yan quan)",
    author: "Tull Dictus",
    publishedDate: "2/6/2025",
    pages: 2,
    coverImage: "http://dummyimage.com/227x100.png/ff4444/ffffff",
    description: "Savory sardines packed in olive oil.",
  },
  {
    id: 21,
    title: "Exit to Hell",
    author: "Odilia Coneron",
    publishedDate: "9/4/2024",
    pages: 79,
    coverImage: "http://dummyimage.com/156x100.png/ff4444/ffffff",
    description: "Convenient carrier for transporting yoga mat.",
  },
  {
    id: 22,
    title: "Fireworks (Hana-bi)",
    author: "Pepi Fippe",
    publishedDate: "3/15/2025",
    pages: 47,
    coverImage: "http://dummyimage.com/151x100.png/cc0000/ffffff",
    description: "A cozy long cardigan designed for layering in any season.",
  },
  {
    id: 23,
    title: "Face in the Crowd, A",
    author: "Iggie Slad",
    publishedDate: "9/28/2024",
    pages: 13,
    coverImage: "http://dummyimage.com/148x100.png/ff4444/ffffff",
    description: "Maintain freshness and dispense cereal easily.",
  },
  {
    id: 24,
    title: "2001: A Space Odyssey",
    author: "Tomaso Rymour",
    publishedDate: "12/21/2024",
    pages: 65,
    coverImage: "http://dummyimage.com/181x100.png/5fa2dd/ffffff",
    description: "Complete crafting kit for kids and adults.",
  },
  {
    id: 25,
    title: "Sonny Boy",
    author: "Larry Tomasello",
    publishedDate: "12/6/2024",
    pages: 75,
    coverImage: "http://dummyimage.com/123x100.png/5fa2dd/ffffff",
    description: "Bottle with infuser for brewing loose-leaf tea on the go.",
  },
  {
    id: 26,
    title: "At the Earth's Core",
    author: "Ulrich Stolli",
    publishedDate: "9/15/2024",
    pages: 92,
    coverImage: "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
    description: "Multi-level cat tree for climbing and scratching.",
  },
  {
    id: 27,
    title: "Silkwood",
    author: "Kylen Whapham",
    publishedDate: "8/19/2024",
    pages: 80,
    coverImage: "http://dummyimage.com/135x100.png/cc0000/ffffff",
    description: "Compact sterilizer for disinfecting small items.",
  },
  {
    id: 28,
    title:
      "Who Can Kill a Child? (a.k.a. Island of the Damned) (¿Quién puede matar a un niño?)",
    author: "Alfy Heavy",
    publishedDate: "7/13/2024",
    pages: 7,
    coverImage: "http://dummyimage.com/149x100.png/dddddd/000000",
    description: "Classic marinara sauce for pasta, pizza, or dipping.",
  },
  {
    id: 29,
    title: "Shoot 'Em Up",
    author: "Levi Ecles",
    publishedDate: "8/22/2024",
    pages: 58,
    coverImage: "http://dummyimage.com/143x100.png/5fa2dd/ffffff",
    description: "Durable skipping rope with adjustable length for workouts.",
  },
  {
    id: 30,
    title: "Black and White in Color (Noirs et blancs en couleur)",
    author: "Chancey Silcox",
    publishedDate: "2/28/2025",
    pages: 7,
    coverImage: "http://dummyimage.com/149x100.png/ff4444/ffffff",
    description: "Organize travel documents, passport, and cards.",
  },
  {
    id: 31,
    title: "Auto Focus",
    author: "Lara Martin",
    publishedDate: "3/18/2025",
    pages: 45,
    coverImage: "http://dummyimage.com/151x100.png/5fa2dd/ffffff",
    description: "Lightweight yoga mat for practicing on the go.",
  },
  {
    id: 32,
    title: "More",
    author: "Benedicto Olkowicz",
    publishedDate: "11/5/2024",
    pages: 91,
    coverImage: "http://dummyimage.com/168x100.png/dddddd/000000",
    description:
      "Marinated chicken skewers with lemon and dill flavor, grilled to perfection.",
  },
  {
    id: 33,
    title: "Sangre de mi sangre (Padre Nuestro)",
    author: "Bobbe Mealand",
    publishedDate: "12/11/2024",
    pages: 32,
    coverImage: "http://dummyimage.com/144x100.png/cc0000/ffffff",
    description: "Ready-to-bake garlic breadsticks, perfect with pasta dishes.",
  },
  {
    id: 34,
    title: "Julie",
    author: "Niall Ratnage",
    publishedDate: "5/29/2024",
    pages: 22,
    coverImage: "http://dummyimage.com/242x100.png/dddddd/000000",
    description: "Rechargeable water flosser for dental hygiene.",
  },
  {
    id: 35,
    title: "Frances Ha",
    author: "Janenna Zuppa",
    publishedDate: "7/6/2024",
    pages: 99,
    coverImage: "http://dummyimage.com/182x100.png/cc0000/ffffff",
    description: "Trendy high-low tee with a relaxed fit, ideal for weekends.",
  },
  {
    id: 36,
    title: "Thrill Ride: The Science of Fun",
    author: "Waring Hendin",
    publishedDate: "8/9/2024",
    pages: 2,
    coverImage: "http://dummyimage.com/138x100.png/5fa2dd/ffffff",
    description:
      "Stackable steamers for healthy cooking of vegetables and seafood.",
  },
  {
    id: 37,
    title: "Oxford Murders, The",
    author: "Shaylah Sowley",
    publishedDate: "5/27/2024",
    pages: 48,
    coverImage: "http://dummyimage.com/236x100.png/cc0000/ffffff",
    description: "Natural air purifiers to absorb odors and moisture.",
  },
  {
    id: 38,
    title: "Eggs",
    author: "Yorke Parman",
    publishedDate: "7/22/2024",
    pages: 20,
    coverImage: "http://dummyimage.com/121x100.png/5fa2dd/ffffff",
    description: "Delicious and hearty black beans, great for soups or salads.",
  },
  {
    id: 39,
    title: "Mortician, The",
    author: "Bruno Moran",
    publishedDate: "7/12/2024",
    pages: 99,
    coverImage: "http://dummyimage.com/110x100.png/cc0000/ffffff",
    description: "Dried tomatoes packed with deep flavor for salads and pasta.",
  },
  {
    id: 40,
    title: "Billy Blazes, Esq.",
    author: "Annaliese Rowe",
    publishedDate: "3/27/2024",
    pages: 9,
    coverImage: "http://dummyimage.com/205x100.png/dddddd/000000",
    description:
      "Relaxed fit joggers made from soft fleece, ideal for lounging or workouts.",
  },
  {
    id: 41,
    title: "Beast, The (La bête)",
    author: "Ardelle Leary",
    publishedDate: "1/27/2025",
    pages: 85,
    coverImage: "http://dummyimage.com/189x100.png/cc0000/ffffff",
    description: "Sweet peach halves packed in juice, great for desserts.",
  },
  {
    id: 42,
    title: "Puffy Chair, The",
    author: "Rorie Kunat",
    publishedDate: "2/8/2025",
    pages: 68,
    coverImage: "http://dummyimage.com/210x100.png/5fa2dd/ffffff",
    description:
      "A tangy marinade for meats and veggies, packed with garlic flavor.",
  },
  {
    id: 43,
    title: "Startup.com",
    author: "Florette Birds",
    publishedDate: "12/6/2024",
    pages: 54,
    coverImage: "http://dummyimage.com/150x100.png/dddddd/000000",
    description: "Removable wall art stickers for home decoration.",
  },
  {
    id: 44,
    title: "The Red Inn",
    author: "Clerc Arundel",
    publishedDate: "10/5/2024",
    pages: 18,
    coverImage: "http://dummyimage.com/245x100.png/5fa2dd/ffffff",
    description: "Stylish faux leather leggings for a trendy outfit.",
  },
  {
    id: 45,
    title: "Independence Day (a.k.a. ID4)",
    author: "Margaretta Mulvenna",
    publishedDate: "6/23/2024",
    pages: 87,
    coverImage: "http://dummyimage.com/198x100.png/ff4444/ffffff",
    description: "Planter with self-watering feature for easy plant care.",
  },
  {
    id: 46,
    title: "Kenny Begins",
    author: "Nev Keeney",
    publishedDate: "10/9/2024",
    pages: 85,
    coverImage: "http://dummyimage.com/202x100.png/dddddd/000000",
    description: "Compact Bluetooth speaker with rich sound quality.",
  },
  {
    id: 47,
    title: "Psycho",
    author: "Florida Milley",
    publishedDate: "2/17/2025",
    pages: 8,
    coverImage: "http://dummyimage.com/207x100.png/ff4444/ffffff",
    description: "Relaxing paint kit with pre-printed canvas for painting.",
  },
  {
    id: 48,
    title: "Mystics in Bali (Leák)",
    author: "Sophi Manion",
    publishedDate: "9/4/2024",
    pages: 38,
    coverImage: "http://dummyimage.com/140x100.png/ff4444/ffffff",
    description: "Creamy cheese with a spicy kick, perfect for sandwiches.",
  },
  {
    id: 49,
    title: "Dog of Flanders, A",
    author: "Magdalen Clemits",
    publishedDate: "5/12/2024",
    pages: 42,
    coverImage: "http://dummyimage.com/101x100.png/cc0000/ffffff",
    description:
      "A hearty soup made with lentils, coconut milk, and a blend of spices for a tropical flavor.",
  },
  {
    id: 50,
    title: "G.I. Joe: Retaliation",
    author: "Reese Lampkin",
    publishedDate: "5/26/2024",
    pages: 39,
    coverImage: "http://dummyimage.com/111x100.png/cc0000/ffffff",
    description: "Soft throw blanket for cozy home decor.",
  },
];
